package agentintegration

import (
	"slices"
	"strings"
	"testing"

	"github.com/research-engineering/agentic-proofkit/internal/kernel/digest"
)

func sourceCapabilities() []Capability {
	result := make([]Capability, len(consumedCommands))
	for index, command := range consumedCommands {
		route := []string{command}
		if command == "change-workflow-plan" {
			route = []string{"change", "plan"}
		}
		if command == "adopt-plan" {
			route = []string{"adopt", "plan"}
		}
		result[index] = Capability{Command: command, Route: route, ContractDigest: digest.SHA256TextRef(command)}
	}
	return result
}

func TestSourceBindsPortableConsumedContracts(t *testing.T) {
	for _, tool := range Tools() {
		t.Run(tool, func(t *testing.T) {
			capabilities := sourceCapabilities()
			document, err := Source(tool, capabilities)
			if err != nil {
				t.Fatal(err)
			}
			again, err := Source(tool, capabilities)
			if err != nil || document != again {
				t.Fatal("identical generation inputs changed the document")
			}
			wantPath := ".agents/skills/agentic-proofkit/SKILL.md"
			if tool == "claude" {
				wantPath = ".claude/skills/agentic-proofkit/SKILL.md"
			}
			if document.path != wantPath || document.metadataBytes != len(frontmatter) || document.bodyBytes != len(document.content)-len(frontmatter) {
				t.Fatal("descriptor path or measured budgets differ")
			}
			if document.metadataBytes > MaximumMetadataBytes || document.bodyBytes > MaximumBodyBytes || document.contentDigest != digest.SHA256TextRef(document.content) {
				t.Fatal("generated bytes violate budget or identity")
			}
			for _, fragment := range []string{"name: agentic-proofkit", "change plan", "adopt plan", "--agent-envelope-mode brief", "detailAccess", "native-evidence-guidance", document.identity} {
				if !strings.Contains(document.content, fragment) {
					t.Fatalf("bootstrap is missing owner fragment %q", fragment)
				}
			}
			for index := range capabilities {
				for _, operand := range []string{"route", "contract"} {
					t.Run(capabilities[index].Command+"/"+operand, func(t *testing.T) {
						changed := sourceCapabilities()
						if operand == "route" {
							changed[index].Route = []string{"replacement", "route"}
						} else {
							changed[index].ContractDigest = digest.SHA256TextRef("changed contract")
						}
						updated, err := Source(tool, changed)
						if err != nil || updated.identity == document.identity || updated.content == document.content {
							t.Fatalf("consumed %s change did not invalidate generated bytes: %v", operand, err)
						}
					})
				}
			}
			capabilities[0].Route[0] = "mutated"
			if document != again {
				t.Fatal("caller mutation changed an already rendered document")
			}
		})
	}
}

func TestSourceRejectsUnboundCapabilities(t *testing.T) {
	t.Run("rendered body budget", func(t *testing.T) {
		capabilities := sourceCapabilities()
		capabilities[0].Route = []string{strings.Repeat("route", MaximumBodyBytes)}
		document, err := Source("codex", capabilities)
		if err == nil || document != (Document{}) || !strings.Contains(err.Error(), "byte budget") {
			t.Fatal("an admitted route beyond the rendered body budget was not rejected")
		}
	})
	for _, mutate := range []func([]Capability) []Capability{
		func(values []Capability) []Capability { return values[1:] },
		func(values []Capability) []Capability { return append(values, values[0]) },
		func(values []Capability) []Capability { values[1] = values[0]; return values },
		func(values []Capability) []Capability { slices.Reverse(values); return values },
		func(values []Capability) []Capability { values[0].Route = []string{"not a route"}; return values },
		func(values []Capability) []Capability { values[0].ContractDigest = "invalid"; return values },
	} {
		if _, err := Source("codex", mutate(sourceCapabilities())); err == nil {
			t.Fatal("invalid consumed capability set was accepted")
		}
	}
	if _, err := Source("", sourceCapabilities()); err == nil {
		t.Fatal("implicit tool selection was accepted")
	}
	toolNames, commands := Tools(), ConsumedCommands()
	toolNames[0], commands[0] = "modified", "modified"
	if Tools()[0] == "modified" || ConsumedCommands()[0] == "modified" {
		t.Fatal("descriptor projection exposes mutable owner state")
	}
}
