package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"

	"github.com/research-engineering/agentic-proofkit/internal/kernel/admission"
	"github.com/research-engineering/agentic-proofkit/internal/kernel/admit"
)

const (
	catalogPath     = "proofkit/command-families.v1.json"
	cliContractPath = "proofkit/cli-contract.v2.json"
	generatedPath   = "internal/app/command_family_catalog_generated.go"
	maxCatalogBytes = 1 << 20
)

var familyIDPattern = regexp.MustCompile(`^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$`)

type catalog struct {
	SchemaVersion        int      `json:"schemaVersion"`
	CatalogID            string   `json:"catalogId"`
	Families             []family `json:"families"`
	HelpForms            []string `json:"helpForms"`
	ReservedHelpOperands []string `json:"reservedHelpOperands"`
	NonClaims            []string `json:"nonClaims"`
}

type family struct {
	FamilyID string   `json:"familyId"`
	Label    string   `json:"label"`
	Purpose  string   `json:"purpose"`
	Commands []string `json:"commands"`
}

func main() {
	check := flag.Bool("check", false, "verify that the generated projection is current")
	flag.Parse()
	if flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "commandfamilygen accepts only --check")
		os.Exit(1)
	}
	root, err := os.Getwd()
	if err == nil {
		err = run(root, *check)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	content, err := render(root)
	if err != nil {
		return err
	}
	outputPath := filepath.Join(root, filepath.FromSlash(generatedPath))
	if check {
		current, err := os.ReadFile(outputPath)
		if err != nil {
			return fmt.Errorf("read generated command family projection: %w", err)
		}
		if !bytes.Equal(current, content) {
			return errors.New("generated command family projection is stale; run go run ./internal/tools/commandfamilygen")
		}
		return nil
	}
	return writeAtomic(outputPath, content)
}

func render(root string) ([]byte, error) {
	source, value, err := readCatalog(filepath.Join(root, filepath.FromSlash(catalogPath)))
	if err != nil {
		return nil, err
	}
	commands, err := readCLICommands(filepath.Join(root, filepath.FromSlash(cliContractPath)))
	if err != nil {
		return nil, err
	}
	if err := validateCatalog(value, commands); err != nil {
		return nil, err
	}
	sum := sha256.Sum256(source)
	var output strings.Builder
	output.WriteString("// Code generated by internal/tools/commandfamilygen; DO NOT EDIT.\n")
	output.WriteString("package app\n\n")
	fmt.Fprintf(&output, "const commandFamilyCatalogSourceSHA256 = %q\n\n", hex.EncodeToString(sum[:]))
	output.WriteString("func generatedCommandFamilyCatalog() commandFamilyCatalog {\n")
	output.WriteString("\treturn commandFamilyCatalog{\n")
	fmt.Fprintf(&output, "\tCatalogID: %q,\n", value.CatalogID)
	output.WriteString("\tFamilies: []commandFamily{\n")
	for _, family := range value.Families {
		fmt.Fprintf(&output, "\t\t{ID: %q, Label: %q, Purpose: %q, Commands: %#v},\n", family.FamilyID, family.Label, family.Purpose, family.Commands)
	}
	output.WriteString("\t},\n")
	fmt.Fprintf(&output, "\tHelpForms: %#v,\n", value.HelpForms)
	fmt.Fprintf(&output, "\tNonClaims: %#v,\n", value.NonClaims)
	fmt.Fprintf(&output, "\tReservedHelpOperands: %#v,\n", value.ReservedHelpOperands)
	fmt.Fprintf(&output, "\tSchemaVersion: %d,\n", value.SchemaVersion)
	output.WriteString("\t}\n")
	output.WriteString("}\n")
	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated command family projection: %w", err)
	}
	return formatted, nil
}

func readCatalog(path string) ([]byte, catalog, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, catalog{}, fmt.Errorf("read command family catalog: %w", err)
	}
	if len(content) > maxCatalogBytes {
		return nil, catalog{}, errors.New("command family catalog exceeds size limit")
	}
	var value catalog
	if err := decodeStrict(content, &value); err != nil {
		return nil, catalog{}, fmt.Errorf("admit command family catalog: %w", err)
	}
	return content, value, nil
}

func readCLICommands(path string) ([]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	raw, err := admission.DecodeJSON(file, maxCatalogBytes)
	if err != nil {
		return nil, err
	}
	object, ok := raw.(map[string]any)
	if !ok {
		return nil, errors.New("CLI contract must be an object")
	}
	records, ok := object["commands"].([]any)
	if !ok {
		return nil, errors.New("CLI contract commands must be an array")
	}
	commands := make([]string, 0, len(records))
	for index, rawRecord := range records {
		record, ok := rawRecord.(map[string]any)
		if !ok {
			return nil, fmt.Errorf("CLI contract command %d must be an object", index)
		}
		command, err := admit.RuleID(record["command"], fmt.Sprintf("CLI contract command %d", index))
		if err != nil {
			return nil, err
		}
		commands = append(commands, command)
	}
	return commands, nil
}

func decodeStrict(content []byte, target any) error {
	raw, err := admission.DecodeJSON(bytes.NewReader(content), int64(len(content)))
	if err != nil {
		return err
	}
	normalized, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	decoder := json.NewDecoder(bytes.NewReader(normalized))
	decoder.DisallowUnknownFields()
	return decoder.Decode(target)
}

func validateCatalog(value catalog, cliCommands []string) error {
	if value.SchemaVersion != 1 || value.CatalogID != "proofkit.command-families.v1" {
		return errors.New("command family catalog identity is invalid")
	}
	if !slices.Equal(value.HelpForms, []string{"help families", "help family <family-id>"}) ||
		!slices.Equal(value.ReservedHelpOperands, []string{"families", "family"}) {
		return errors.New("command family help grammar is invalid")
	}
	if err := validateSortedText(value.NonClaims, "catalog nonClaims", 1, 16); err != nil {
		return err
	}
	if len(value.Families) == 0 || !sort.SliceIsSorted(value.Families, func(i, j int) bool { return value.Families[i].FamilyID < value.Families[j].FamilyID }) {
		return errors.New("command families must be non-empty and sorted by familyId")
	}
	seenFamilies := map[string]struct{}{}
	seenCommands := map[string]struct{}{}
	for index, family := range value.Families {
		if _, err := admit.RuleID(family.FamilyID, fmt.Sprintf("family %d familyId", index)); err != nil {
			return err
		}
		if !familyIDPattern.MatchString(family.FamilyID) {
			return fmt.Errorf("family %d familyId must be canonical lowercase kebab case", index)
		}
		if _, duplicate := seenFamilies[family.FamilyID]; duplicate {
			return errors.New("command family ids must be unique")
		}
		seenFamilies[family.FamilyID] = struct{}{}
		label, err := admit.NonEmptyText(family.Label, fmt.Sprintf("family %s label", family.FamilyID))
		if err != nil || label != family.Label {
			return fmt.Errorf("family %s label must be canonical text", family.FamilyID)
		}
		purpose, err := admit.NonEmptyText(family.Purpose, fmt.Sprintf("family %s purpose", family.FamilyID))
		if err != nil || purpose != family.Purpose {
			return fmt.Errorf("family %s purpose must be canonical text", family.FamilyID)
		}
		if err := validateSortedText(family.Commands, "family "+family.FamilyID+" commands", 1, 8); err != nil {
			return err
		}
		for _, command := range family.Commands {
			if _, err := admit.RuleID(command, "family command"); err != nil {
				return err
			}
			if _, duplicate := seenCommands[command]; duplicate {
				return fmt.Errorf("command %s belongs to multiple families", command)
			}
			seenCommands[command] = struct{}{}
		}
	}
	cliCommandSet := map[string]struct{}{}
	for _, command := range cliCommands {
		if _, duplicate := cliCommandSet[command]; duplicate {
			return fmt.Errorf("CLI command %s is duplicated", command)
		}
		cliCommandSet[command] = struct{}{}
	}
	for _, reserved := range value.ReservedHelpOperands {
		if _, collision := cliCommandSet[reserved]; collision {
			return fmt.Errorf("reserved help operand %s collides with a command", reserved)
		}
	}
	if len(seenCommands) != len(cliCommands) {
		return fmt.Errorf("command family coverage count=%d want %d", len(seenCommands), len(cliCommands))
	}
	for _, command := range cliCommands {
		if _, ok := seenCommands[command]; !ok {
			return fmt.Errorf("CLI command %s is missing from the family catalog", command)
		}
	}
	return nil
}

func validateSortedText(values []string, context string, minimum int, maximum int) error {
	if len(values) < minimum || len(values) > maximum || !slices.IsSorted(values) {
		return fmt.Errorf("%s must contain %d..%d sorted unique values", context, minimum, maximum)
	}
	for index, value := range values {
		admitted, err := admit.NonEmptyText(value, fmt.Sprintf("%s item %d", context, index))
		if err != nil || admitted != value {
			return fmt.Errorf("%s contains non-canonical text", context)
		}
		if index > 0 && values[index-1] == value {
			return fmt.Errorf("%s must contain %d..%d sorted unique values", context, minimum, maximum)
		}
	}
	return nil
}

func writeAtomic(path string, content []byte) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".command-family-catalog-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(content); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
