package app

import (
	"bytes"
	"context"
	"maps"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"github.com/research-engineering/agentic-proofkit/internal/command/agentintegration"
	"github.com/research-engineering/agentic-proofkit/internal/kernel/cliexec"
	"github.com/research-engineering/agentic-proofkit/internal/kernel/digest"
	"github.com/research-engineering/agentic-proofkit/internal/testsupport/commandcoverage"
)

func integrationDocument(t *testing.T, tool string) agentintegration.Document {
	t.Helper()
	capabilities, err := integrationCapabilities(commandDescriptorByName, generatedCommandContractMetadataByName)
	if err != nil {
		t.Fatal(err)
	}
	document, err := agentintegration.Source(tool, capabilities)
	if err != nil {
		t.Fatal(err)
	}
	return document
}

func TestIntegrationSourceCLI(t *testing.T) {
	commandcoverage.SemanticRoute(t, "proofkit.command_coverage.source_oracle.v1.055752742369677475265762786661152229127557861085124179111305077873855100236870")
	for _, tool := range agentintegration.Tools() {
		document := integrationDocument(t, tool)
		for _, format := range []string{"json", "text"} {
			code, output, diagnostic := executeAgentWorkflowCLI(t, []string{"integration", "source", "--tool", tool, "--format", format}, panicReader{}, PresentationCapabilities{StdoutIsTTY: true})
			if code != 0 || diagnostic != "" || strings.Contains(output, "\x1b") {
				t.Fatalf("source format=%s exit=%d diagnostic=%q", format, code, diagnostic)
			}
			if format == "text" {
				if output != document.Content() {
					t.Fatal("text source differs from exact generated bytes")
				}
			} else {
				value := decodeCLIJSON(t, output).(map[string]any)
				if value["content"] != document.Content() || value["kind"] != "proofkit.integration-source.v1" || value["tool"] != tool {
					t.Fatal("source command did not emit the selected generator document")
				}
			}
		}
	}
	for _, args := range [][]string{
		{"integration", "source"},
		{"integration", "source", "--tool", "all"},
		{"integration", "source", "--tool", "codex", "--tool", "claude"},
		{"integration", "source", "--tool", "codex", "--repo-root", "unread"},
		{"integration", "source", "--tool", "codex", "--input", "-"},
		{"integration", "source", "--tool", "codex", "--output", "unused"},
		{"--json-layout", "compact", "integration", "source", "--tool", "codex", "--format", "text"},
	} {
		code, output, diagnostic := executeAgentWorkflowCLI(t, args, panicReader{}, PresentationCapabilities{})
		if code != 1 || output != "" || diagnostic == "" {
			t.Fatal("invalid generation invocation was not rejected before output")
		}
	}
}

func TestIntegrationCheckCLI(t *testing.T) {
	commandcoverage.SemanticRoute(t, "proofkit.command_coverage.source_oracle.v1.115408364061752394702935199140172268554813555954760274834640853529071448021786")
	for _, tool := range agentintegration.Tools() {
		t.Run(tool, func(t *testing.T) {
			root := t.TempDir()
			document := integrationDocument(t, tool)
			path := filepath.Join(root, filepath.FromSlash(document.JSONValue()["targetPath"].(string)))
			for _, state := range []string{"missing", "current", "stale", "invalid"} {
				if state != "missing" {
					if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
						t.Fatal(err)
					}
					content := document.Content()
					if state == "stale" {
						content += "owner edit\n"
					}
					if state == "invalid" {
						content = "\x00"
					}
					if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
						t.Fatal(err)
					}
				}
				before, beforeErr := os.ReadFile(path)
				for _, format := range []string{"json", "text"} {
					code, output, diagnostic := executeAgentWorkflowCLI(t, []string{"integration", "check", "--tool", tool, "--repo-root", root, "--format", format}, panicReader{}, PresentationCapabilities{})
					wantCode := 2
					if state == "current" {
						wantCode = 0
					}
					if code != wantCode || diagnostic != "" || strings.Contains(output, root) || strings.Contains(output, "owner edit") {
						t.Fatalf("check state=%s format=%s exit=%d diagnosticPresent=%t", state, format, code, diagnostic != "")
					}
					if format == "json" {
						value := decodeCLIJSON(t, output).(map[string]any)
						if value["kind"] != "proofkit.integration-check.v1" || value["state"] != state || value["integrationId"] != document.JSONValue()["integrationId"] {
							t.Fatal("check result does not classify selected generated file")
						}
					} else if !strings.Contains(output, state) || strings.Contains(output, "\x1b") {
						t.Fatal("check text does not preserve state")
					}
				}
				after, afterErr := os.ReadFile(path)
				if !bytes.Equal(before, after) || (beforeErr == nil) != (afterErr == nil) {
					t.Fatal("read-only check mutated the selected entry")
				}
			}
			code, output, diagnostic := executeAgentWorkflowCLI(t, []string{"integration", "check", "--tool", "invalid", "--repo-root", filepath.Join(root, "absent")}, panicReader{}, PresentationCapabilities{})
			if code != 1 || output != "" || !strings.Contains(diagnostic, "--tool") {
				t.Fatal("tool admission did not dominate repository I/O")
			}
		})
	}
}

func TestIntegrationCommandsExactRootShapes(t *testing.T) {
	for _, operation := range []string{"source", "check"} {
		args := []string{"integration", operation, "--tool", "codex"}
		keys := []string{"bodyBytes", "capabilityDigest", "content", "contentDigest", "integrationId", "kind", "metadataBytes", "nonClaims", "schemaVersion", "targetPath", "tool"}
		wantCode := 0
		if operation == "check" {
			args = append(args, "--repo-root", t.TempDir())
			keys = []string{"expectedContentDigest", "integrationId", "kind", "nonClaims", "schemaVersion", "state", "targetPath", "tool"}
			wantCode = 2
		}
		code, output, diagnostic := executeAgentWorkflowCLI(t, args, panicReader{}, PresentationCapabilities{})
		if code != wantCode || diagnostic != "" {
			t.Fatalf("root shape command exit=%d", code)
		}
		assertExactObjectKeys(t, decodeCLIJSON(t, output).(map[string]any), keys, operation)
	}
}

func TestIntegrationSourcesAreCarrierIndependent(t *testing.T) {
	for _, tool := range agentintegration.Tools() {
		for _, format := range []string{"json", "text"} {
			var previous string
			for _, profile := range []string{cliexec.ProfilePath, cliexec.ProfileNPMOffline, cliexec.ProfilePythonModule} {
				python := ""
				if profile == cliexec.ProfilePythonModule {
					python = "/isolated/consumer/bin/python"
				}
				renderer, err := cliexec.AdmitLauncherProfile(profile, python)
				if err != nil {
					t.Fatal(err)
				}
				var stdout, stderr bytes.Buffer
				code := RunWithRenderer(context.Background(), []string{"integration", "source", "--tool", tool, "--format", format}, panicReader{}, &stdout, &stderr, renderer)
				if code != 0 || stderr.Len() != 0 || previous != "" && previous != stdout.String() {
					t.Fatal("process-local launcher changed portable source bytes")
				}
				previous = stdout.String()
			}
		}
	}
}

func TestIntegrationCapabilityIdentityScope(t *testing.T) {
	base, err := integrationCapabilities(commandDescriptorByName, generatedCommandContractMetadataByName)
	if err != nil {
		t.Fatal(err)
	}
	metadata := maps.Clone(generatedCommandContractMetadataByName)
	unconsumed := metadata["text-policy"]
	unconsumed.OutputContractSHA256 = digest.SHA256TextRef("changed unconsumed record")
	metadata["text-policy"] = unconsumed
	unchanged, err := integrationCapabilities(commandDescriptorByName, metadata)
	if err != nil || !reflect.DeepEqual(base, unchanged) {
		t.Fatal("unconsumed metadata altered integration capabilities")
	}
	for _, command := range agentintegration.ConsumedCommands() {
		for _, operand := range []string{"route", "flags", "contract"} {
			descriptors := maps.Clone(commandDescriptorByName)
			descriptor := descriptors[command].clone()
			metadata := maps.Clone(generatedCommandContractMetadataByName)
			switch operand {
			case "route":
				descriptor.routeTokens = []string{"new", "route"}
			case "flags":
				descriptor.requiredFlags = append(descriptor.requiredFlags, "--new-flag")
			case "contract":
				changed := metadata[command]
				changed.OutputContractSHA256 = digest.SHA256TextRef("changed consumed record")
				metadata[command] = changed
			}
			descriptors[command] = descriptor
			changed, err := integrationCapabilities(descriptors, metadata)
			if err != nil || reflect.DeepEqual(base, changed) {
				t.Fatalf("consumed %s/%s change was not bound", command, operand)
			}
		}
	}
	delete(metadata, "next")
	if _, err := integrationCapabilities(commandDescriptorByName, metadata); err == nil {
		t.Fatal("missing consumed contract was accepted")
	}
}

func TestIntegrationCancellationBeforeOutput(t *testing.T) {
	for _, format := range []string{"json", "text"} {
		ctx, cancel := context.WithCancel(context.Background())
		cancel()
		var stdout, stderr bytes.Buffer
		code := Run(ctx, []string{"integration", "source", "--tool", "codex", "--format", format}, panicReader{}, &stdout, &stderr)
		if code != 1 || stdout.Len() != 0 || !strings.Contains(stderr.String(), "cancelled") {
			t.Fatal("cancelled source command began emitting output")
		}
	}
}
