// Code generated by internal/tools/commandfamilygen; DO NOT EDIT.
package app

const commandFamilyCatalogSourceSHA256 = "5373aceca3b2d69d0d687e68b3801c6b914c2259f71569e476aa7a38383cd166"

func generatedCommandFamilyCatalog() commandFamilyCatalog {
	return commandFamilyCatalog{
		CatalogID: "proofkit.command-families.v1",
		Families: []commandFamily{
			{ID: "adoption-lifecycle", Label: "Adoption lifecycle", Purpose: "Select and assess repository adoption stages.", Commands: []string{"adoption-checklist", "adoption-doctor", "adoption-workflow-plan", "gradual-adoption", "gradual-adoption-bootstrap", "gradual-adoption-guidance", "init", "pilot-admission"}},
			{ID: "cli-metadata-and-conformance", Label: "CLI metadata and conformance", Purpose: "Expose, route, generate, and self-check CLI contract surfaces.", Commands: []string{"agent-route", "conformance-profile", "help", "json-report-cli-adapter-source", "self-check"}},
			{ID: "deployment-and-readiness", Label: "Deployment and readiness", Purpose: "Admit deployment evidence and bounded closeout decisions.", Commands: []string{"branch-authority", "completion-criteria", "deployment-evidence-admission", "readiness-closeout"}},
			{ID: "migration-and-retirement", Label: "Migration and retirement", Purpose: "Prove parity and plan retirement of consumer-local infrastructure.", Commands: []string{"migration-parity-admission", "migration-plan"}},
			{ID: "proof-artifact-governance", Label: "Proof artifact governance", Purpose: "Govern custom rules, document lifecycle, freshness, and witness plans.", Commands: []string{"custom-rule-boundary", "document-lifecycle-boundary", "rendered-artifact-freshness", "witness-plan", "witness-scheduler-plan"}},
			{ID: "proof-binding-topology", Label: "Proof binding topology", Purpose: "Admit, resolve, partition, and inspect requirement proof topology.", Commands: []string{"binding-partition", "evidence-graph", "proof-slice", "requirement-bindings", "requirement-proof-resolver", "requirement-proof-source-set", "spec-proof-bundle-admission"}},
			{ID: "receipt-authority", Label: "Receipt authority", Purpose: "Admit receipts, producer compatibility, currentness, and trust classes.", Commands: []string{"producer-policy-self-proof", "proof-receipt-admission", "receipt-currentness-scope", "receipt-producer-admission", "receipt-trust-class"}},
			{ID: "release-artifact-consumption", Label: "Release artifact consumption", Purpose: "Check package release facts and external or registry consumption.", Commands: []string{"external-consumer", "registry-consumer", "registry-consumer-proof-input-compose", "release-authority"}},
			{ID: "repository-facts-and-scanning", Label: "Repository facts and scanning", Purpose: "Admit explicit repository facts and bounded policy scans.", Commands: []string{"repo-profile-admission", "secret-scan", "text-policy", "typescript-public-api-surfaces", "workspace-manifest-facts"}},
			{ID: "requirement-context-and-traceability", Label: "Requirement context and traceability", Purpose: "Compose bounded semantic context and derive diff and traceability projections.", Commands: []string{"requirement-context-compose", "requirement-context-slice", "requirement-semantic-diff", "requirement-traceability-graph"}},
			{ID: "requirement-navigation-and-rendering", Label: "Requirement navigation and rendering", Purpose: "Build and present requirement, proof, and coverage views.", Commands: []string{"requirement-browser-server", "requirement-coverage-view", "requirement-proof-view", "requirement-source-view", "requirement-spec-tree", "requirement-spec-tree-view"}},
			{ID: "requirement-source-lifecycle", Label: "Requirement source lifecycle", Purpose: "Author, admit, transition, and check requirement source claims.", Commands: []string{"requirement-authoring-plan", "requirement-source-admission", "requirement-source-transition", "spec-overview-claims"}},
			{ID: "scaffolding-and-capability-capture", Label: "Scaffolding and capability capture", Purpose: "Produce candidate adoption structures and capability seeds.", Commands: []string{"adoption-contract-envelope", "capability-map-admission", "scaffold-profile-plan", "scaffold-project-structure", "stack-preset"}},
			{ID: "selective-evidence-and-obligations", Label: "Selective evidence and obligations", Purpose: "Admit selective evidence and decide proof obligations.", Commands: []string{"obligation-decision", "proof-obligation-algebra", "selective-gate-evidence", "selective-gate-obligation-decision-input"}},
			{ID: "selective-impact-planning", Label: "Selective impact planning", Purpose: "Convert explicit change facts into bounded verification plans.", Commands: []string{"changed-path-set", "impact", "requirement-impact-input-compose", "selective-gate-plan"}},
			{ID: "test-evidence-and-coverage-input", Label: "Test evidence and coverage input", Purpose: "Admit test evidence and compose coverage inputs.", Commands: []string{"requirement-coverage-input-compose", "test-evidence-inventory"}},
			{ID: "workspace-topology-and-package-policy", Label: "Workspace topology and package policy", Purpose: "Model workspace topology, shards, and package runtime policy.", Commands: []string{"package-runtime-dependency-admission", "workspace-changed-package-plan", "workspace-registry", "workspace-shard-partition"}},
		},
		HelpForms:            []string{"help families", "help family <family-id>"},
		NonClaims:            []string{"Command families do not change leaf command dispatch or execution authority.", "Command families do not infer which command a caller should execute.", "Command families group the public command inventory for navigation only."},
		ReservedHelpOperands: []string{"families", "family"},
		SchemaVersion:        1,
	}
}
