// Code generated by internal/tools/commandcontractgen; DO NOT EDIT.
package stackpreset

const presetContractSourceSHA256 = "9dff6b0920dfd7508df850db714726413e8fb2b6c620da853cc155a72b1c10a8"

var presetIDs = []string{"agentic_runtime_repo", "generated_docs_contract_repo", "python_service", "python_typescript_service", "typescript_monorepo", "typescript_workspace"}
