// Code generated by internal/tools/commandcontractgen; DO NOT EDIT.
package stackpreset

const presetContractSourceSHA256 = "154b374f52bc51a157266ca84eeb75dde97daec4c401e38817e3d0ca2be49b0c"

var presetIDs = []string{"agentic_runtime_repo", "generated_docs_contract_repo", "python_service", "python_typescript_service", "typescript_monorepo", "typescript_workspace"}
