// Code generated by internal/tools/commandcontractgen; DO NOT EDIT.
package stackpreset

const presetContractSourceSHA256 = "3e112c9dc18df65123b84369fff689a43cb8255746cd6fce024ddc0870bb4b80"

var presetIDs = []string{"agentic_runtime_repo", "generated_docs_contract_repo", "python_service", "python_typescript_service", "typescript_monorepo", "typescript_workspace"}
