package jsonreportcliadaptersource

import (
	"fmt"

	"github.com/research-engineering/agentic-proofkit/internal/kernel/digest"
)

const LanguageTypeScript = "typescript"
const FormatJSON = "json"

var exportedSymbols = []string{
	"ProofkitCommandRunOptions",
	"ProofkitJsonCommandResult",
	"ProofkitJsonRecord",
	"ProofkitJsonReportCliFlag",
	"ProofkitJsonReportCliOptions",
	"ProofkitJsonReportCliParseConfig",
	"ProofkitJsonReportOutputOptions",
	"ProofkitJsonValue",
	"ProofkitProcessResult",
	"ProofkitReportInputReadOptions",
	"ProofkitReportRecord",
	"ProofkitTextCommandResult",
	"formatProofkitCliError",
	"isProofkitJsonRecord",
	"parseProofkitJsonReportCli",
	"parseProofkitJsonStrict",
	"proofkitStableJsonString",
	"proofkitStableJsonValue",
	"readProofkitJsonReportInput",
	"readProofkitTextReportInput",
	"runProofkitJsonCommand",
	"runProofkitJsonReportCliMain",
	"runProofkitNoInputJsonCommand",
	"runProofkitTextCommand",
	"writeProofkitJsonReportOutput",
}

var nonClaims = []string{
	"Generated adapter source does not publish a package-root SDK or npm subpath API.",
	"Generated adapter source does not resolve package pins, lockfiles, repository roots, or installed binary paths.",
	"Generated adapter source does not scan repositories, execute native witnesses beyond explicitly requested CLI subprocesses, decide proof freshness, approve merge, or approve rollout.",
	"Generated adapter source rejects duplicate JSON keys and unsafe integer tokens before JSON.parse, but it does not replace Go command admission.",
	"Consumers own whether to commit generated source and how to prove generated-source freshness.",
}

type Bundle struct {
	Language string
	Format   string
}

func Build(language string, format string) (map[string]any, error) {
	if language != LanguageTypeScript {
		return nil, fmt.Errorf("--language must be typescript")
	}
	if format != "" && format != FormatJSON {
		return nil, fmt.Errorf("--format must be json")
	}
	return Bundle{Language: language, Format: FormatJSON}.JSONValue(), nil
}

func (bundle Bundle) JSONValue() map[string]any {
	source := TypeScriptSource()
	return map[string]any{
		"schemaVersion":   1,
		"artifactKind":    "proofkit.json-report-cli-adapter-source",
		"generatorId":     "proofkit.json-report-cli-adapter-source.typescript.v1",
		"language":        bundle.Language,
		"format":          bundle.Format,
		"sourceFileName":  "proofkit-json-report-cli-adapter.ts",
		"source":          source,
		"sourceSha256":    digest.SHA256TextRef(source),
		"exportedSymbols": stringsToAny(exportedSymbols),
		"summary": map[string]any{
			"exportedSymbolCount": len(exportedSymbols),
			"lineCount":           sourceLineCount(source),
			"publicContract":      "CLI/JSON plus generated source; no package-root SDK contract",
		},
		"nonClaims": stringsToAny(nonClaims),
	}
}

func TypeScriptSource() string {
	return typeScriptSource
}

func stringsToAny(values []string) []any {
	out := make([]any, 0, len(values))
	for _, value := range values {
		out = append(out, value)
	}
	return out
}

func sourceLineCount(source string) int {
	if source == "" {
		return 0
	}
	count := 1
	for _, runeValue := range source {
		if runeValue == '\n' {
			count++
		}
	}
	if source[len(source)-1] == '\n' {
		count--
	}
	return count
}

const typeScriptSource = `/* Generated by agentic-proofkit json-report-cli-adapter-source.
 * Public contract: local generated source that drives the Proofkit CLI/JSON ABI.
 * Non-claim: this file does not publish an agentic-proofkit package SDK.
 */

import { spawnSync } from "node:child_process";
import { closeSync, fstatSync, openSync, readSync, writeFileSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";

const defaultMaxBuffer = 64 * 1024 * 1024;
const defaultMaxInputBytes = 8 * 1024 * 1024;

export type ProofkitJsonValue =
  | null
  | boolean
  | number
  | string
  | readonly ProofkitJsonValue[]
  | { readonly [key: string]: ProofkitJsonValue };

export type ProofkitJsonRecord = { readonly [key: string]: unknown };

export type ProofkitReportRecord = ProofkitJsonRecord & {
  readonly diagnostics: readonly ProofkitJsonRecord[];
  readonly nonClaims: readonly string[];
  readonly reportId: string;
  readonly reportKind: string;
  readonly ruleResults: readonly ProofkitJsonRecord[];
  readonly schemaVersion: 1;
  readonly state: "blocked" | "failed" | "passed";
  readonly summary: ProofkitJsonRecord;
};

export interface ProofkitJsonReportCliFlag<Key extends string = string> {
  readonly flag: string;
  readonly key: Key;
  readonly required?: boolean;
}

export interface ProofkitJsonReportCliParseConfig<Key extends string = string> {
  readonly flags: readonly ProofkitJsonReportCliFlag<Key>[];
  readonly helpText?: string;
  readonly exitHelp?: (code: number) => never;
  readonly missingRequiredArgumentsMessage?: (flags: readonly string[]) => string;
  readonly missingValueMessage?: (flag: string) => string;
  readonly unknownArgumentMessage?: (argument: string) => string;
  readonly writeHelp?: (text: string) => void;
}

export type ProofkitJsonReportCliOptions<Key extends string = string> = {
  readonly outputPath: string | null;
} & { readonly [K in Key]: string | null };

export interface ProofkitReportInputReadOptions {
  readonly failureMessagePrefix?: string;
  readonly maxInputBytes?: number;
}

export interface ProofkitJsonReportOutputOptions {
  readonly writeStdout?: (text: string) => void;
}

export interface ProofkitCommandRunOptions {
  readonly binaryPath: string;
  readonly cwd: string;
  readonly env?: Readonly<Record<string, string | undefined>>;
  readonly inputMode?: "none" | "required";
  readonly maxBuffer?: number;
}

export interface ProofkitProcessResult {
  readonly status: number | null;
  readonly stdout: string;
  readonly stderr: string;
}

export type ProofkitJsonCommandResult<T = unknown> = ProofkitProcessResult & {
  readonly value: T;
};

export type ProofkitTextCommandResult = ProofkitProcessResult & {
  readonly text: string;
};

export function isProofkitJsonRecord(value: unknown): value is ProofkitJsonRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function proofkitStableJsonValue(value: unknown): ProofkitJsonValue {
  if (value === null || typeof value === "boolean" || typeof value === "string") {
    return value;
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      throw new Error("stable JSON value must not contain non-finite numbers");
    }
    if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
      throw new Error("stable JSON value must not contain unsafe integer numbers");
    }
    return value;
  }
  if (Array.isArray(value)) {
    return value.map((item) => proofkitStableJsonValue(item));
  }
  if (typeof value === "object") {
    const record = value as Record<string, unknown>;
    const output: Record<string, ProofkitJsonValue> = {};
    for (const key of Object.keys(record).sort()) {
      if (key.length === 0 || key.includes("\0")) {
        throw new Error("stable JSON object keys must be non-empty text");
      }
      output[key] = proofkitStableJsonValue(record[key]);
    }
    return output;
  }
  throw new Error("stable JSON value must be JSON-serializable");
}

export function proofkitStableJsonString(value: unknown): string {
  return JSON.stringify(proofkitStableJsonValue(value), null, 2) + "\n";
}

export function formatProofkitCliError(error: unknown): string {
  return redactSecretLikeText(error instanceof Error ? error.message : String(error));
}

export function parseProofkitJsonReportCli<Key extends string>(
  argv: readonly string[],
  config: ProofkitJsonReportCliParseConfig<Key>,
): ProofkitJsonReportCliOptions<Key> {
  const parsed: Record<string, string | null> = { outputPath: null };
  const flagByName = new Map<string, ProofkitJsonReportCliFlag<Key>>();
  for (const flag of config.flags ?? []) {
    if (flagByName.has(flag.flag)) {
      throw new Error("duplicate CLI flag " + flag.flag);
    }
    flagByName.set(flag.flag, flag);
    parsed[flag.key] = null;
  }
  for (let index = 0; index < argv.length; index += 1) {
    const argument = argv[index];
    if (argument === "--help") {
      (config.writeHelp ?? ((text: string) => process.stdout.write(text)))(config.helpText ?? "");
      (config.exitHelp ?? ((code: number) => process.exit(code)))(0);
    }
    if (argument === "--output") {
      parsed.outputPath = nextCliValue(argv, index, argument, config);
      index += 1;
      continue;
    }
    const flag = flagByName.get(argument ?? "");
    if (flag !== undefined) {
      parsed[flag.key] = nextCliValue(argv, index, argument ?? "", config);
      index += 1;
      continue;
    }
    throw new Error((config.unknownArgumentMessage ?? ((value: string) => "unknown argument " + value))(argument ?? ""));
  }
  const missing = [...flagByName.values()]
    .filter((flag) => flag.required === true && parsed[flag.key] === null)
    .map((flag) => flag.flag);
  if (missing.length > 0) {
    throw new Error((config.missingRequiredArgumentsMessage ?? ((flags: readonly string[]) => "missing required argument(s): " + flags.join(", ")))(missing));
  }
  return parsed as ProofkitJsonReportCliOptions<Key>;
}

export function parseProofkitJsonStrict(source: string): unknown {
  const scanner = new ProofkitJsonScanner(source);
  scanner.parseValue();
  scanner.skipWhitespace();
  if (!scanner.isEnd()) {
    throw new Error("invalid JSON input: multiple JSON values");
  }
  return JSON.parse(source);
}

export function readProofkitJsonReportInput(filePath: string, options: ProofkitReportInputReadOptions = {}): unknown {
  try {
    return parseProofkitJsonStrict(readProofkitBoundedTextFile(filePath, options));
  } catch (error) {
    throw new Error(formatReadFailure(filePath, error, options));
  }
}

export function readProofkitTextReportInput(filePath: string, options: ProofkitReportInputReadOptions = {}): string {
  try {
    return readProofkitBoundedTextFile(filePath, options);
  } catch (error) {
    throw new Error(formatReadFailure(filePath, error, options));
  }
}

function readProofkitBoundedTextFile(filePath: string, options: ProofkitReportInputReadOptions): string {
  const maxInputBytes = options.maxInputBytes ?? defaultMaxInputBytes;
  if (!Number.isSafeInteger(maxInputBytes) || maxInputBytes < 0) {
    throw new Error("maxInputBytes must be a non-negative safe integer");
  }
  const fd = openSync(filePath, "r");
  try {
    const stat = fstatSync(fd);
    if (!stat.isFile()) {
      throw new Error("input path must be a regular file");
    }
    if (stat.size > maxInputBytes) {
      throw new Error("input file exceeds maxInputBytes");
    }
    const chunks: Buffer[] = [];
    const chunk = Buffer.alloc(Math.min(64 * 1024, maxInputBytes + 1));
    let total = 0;
    for (;;) {
      const remaining = maxInputBytes + 1 - total;
      if (remaining <= 0) {
        throw new Error("input file exceeds maxInputBytes");
      }
      const bytesRead = readSync(fd, chunk, 0, Math.min(chunk.length, remaining), null);
      if (bytesRead === 0) {
        break;
      }
      total += bytesRead;
      if (total > maxInputBytes) {
        throw new Error("input file exceeds maxInputBytes");
      }
      chunks.push(Buffer.from(chunk.subarray(0, bytesRead)));
    }
    return Buffer.concat(chunks, total).toString("utf8");
  } finally {
    closeSync(fd);
  }
}

export function writeProofkitJsonReportOutput(
  value: unknown,
  outputPath?: string | null,
  options: ProofkitJsonReportOutputOptions = {},
): void {
  const output = proofkitStableJsonString(value);
  if (outputPath === null || outputPath === undefined) {
    (options.writeStdout ?? ((text: string) => process.stdout.write(text)))(output);
    return;
  }
  writeFileSync(outputPath, output);
}

export function runProofkitJsonReportCliMain(input: {
  readonly argv?: readonly string[];
  readonly run: (argv: readonly string[]) => number | Promise<number>;
  readonly writeError?: (text: string) => void;
}): Promise<void> | undefined {
  const writeError = input.writeError ?? ((text: string) => process.stderr.write(text));
  try {
    const result = input.run(input.argv ?? process.argv.slice(2));
    if (typeof result === "number") {
      process.exitCode = result;
      return undefined;
    }
    return Promise.resolve(result).then(
      (exitCode) => {
        process.exitCode = exitCode;
      },
      (error: unknown) => {
        writeError(formatProofkitCliError(error) + "\n");
        process.exitCode = 1;
      },
    );
  } catch (error) {
    writeError(formatProofkitCliError(error) + "\n");
    process.exitCode = 1;
    return undefined;
  }
}

export function runProofkitJsonCommand<T = unknown>(
  command: string,
  input: unknown,
  args: readonly string[],
  options: ProofkitCommandRunOptions,
): ProofkitJsonCommandResult<T> {
  const child = runProofkitCommand(command, input, args, options);
  if (child.status !== 0 && child.stdout.trim().length === 0) {
    throw new Error(formatProofkitCliError(child.stderr.trim() || command + " failed with exit code " + String(child.status)));
  }
  const outputPath = outputPathFromArgs(command, args);
  const jsonText = child.stdout.trim().length === 0 && outputPath !== null && outputPath !== "-" ?
    readProofkitTextReportInput(resolveOutputPath(options.cwd, outputPath)) :
    child.stdout;
  try {
    return {
      status: child.status,
      stdout: child.stdout,
      stderr: child.stderr,
      value: parseProofkitJsonStrict(jsonText) as T,
    };
  } catch (error) {
    throw new Error(command + " produced invalid JSON: " + formatProofkitCliError(error));
  }
}

export function runProofkitNoInputJsonCommand<T = unknown>(
  command: string,
  args: readonly string[],
  options: ProofkitCommandRunOptions,
): ProofkitJsonCommandResult<T> {
  return runProofkitJsonCommand<T>(command, null, args, {...options, inputMode: "none"});
}

export function runProofkitTextCommand(
  command: string,
  input: unknown,
  args: readonly string[],
  options: ProofkitCommandRunOptions,
): ProofkitTextCommandResult {
  const child = runProofkitCommand(command, input, args, options);
  return {
    status: child.status,
    stdout: child.stdout,
    stderr: child.stderr,
    text: child.stdout,
  };
}

function runProofkitCommand(command: string, input: unknown, args: readonly string[], options: ProofkitCommandRunOptions) {
  admitCommand(command);
  admitRunOptions(options);
  const childArgs = options.inputMode === "none" ? [command, ...args] : [command, "--input", "-", ...args];
  const child = spawnSync(options.binaryPath, childArgs, {
    cwd: options.cwd,
    encoding: "utf8",
    env: options.env,
    input: options.inputMode === "none" ? undefined : proofkitStableJsonString(input),
    maxBuffer: options.maxBuffer ?? defaultMaxBuffer,
  });
  if (child.error !== undefined) {
    throw child.error;
  }
  return child;
}

function outputPathFromArgs(command: string, args: readonly string[]): string | null {
  if (command !== "requirement-spec-tree-view") {
    return null;
  }
  for (let index = 0; index < args.length; index += 1) {
    if (args[index] === "--output") {
      const value = args[index + 1];
      if (value === undefined || value.startsWith("--")) {
        throw new Error("--output requires a value");
      }
      return value;
    }
  }
  return null;
}

function resolveOutputPath(cwd: string, outputPath: string): string {
  return isAbsolute(outputPath) ? outputPath : resolve(cwd, outputPath);
}

class ProofkitJsonScanner {
  private index = 0;
  private readonly source: string;

  public constructor(source: string) {
    this.source = source;
  }

  public isEnd(): boolean {
    return this.index >= this.source.length;
  }

  public skipWhitespace(): void {
    while (!this.isEnd() && /\s/u.test(this.source[this.index] ?? "")) {
      this.index += 1;
    }
  }

  public parseValue(): void {
    this.skipWhitespace();
    const char = this.source[this.index];
    if (char === undefined) {
      throw new Error("invalid JSON input: unexpected end");
    }
    if (char === "{") {
      this.parseObject();
      return;
    }
    if (char === "[") {
      this.parseArray();
      return;
    }
    if (char === "\"") {
      this.parseString();
      return;
    }
    if (char === "-" || (char >= "0" && char <= "9")) {
      this.parseNumber();
      return;
    }
    if (this.consumeLiteral("true") || this.consumeLiteral("false") || this.consumeLiteral("null")) {
      return;
    }
    throw new Error("invalid JSON input: unexpected token");
  }

  private parseObject(): void {
    this.index += 1;
    const seen = new Set<string>();
    this.skipWhitespace();
    if (this.source[this.index] === "}") {
      this.index += 1;
      return;
    }
    while (!this.isEnd()) {
      this.skipWhitespace();
      if (this.source[this.index] !== "\"") {
        throw new Error("invalid JSON input: object key must be a string");
      }
      const key = this.parseString();
      if (seen.has(key)) {
        throw new Error("invalid JSON input: duplicate object key");
      }
      seen.add(key);
      this.skipWhitespace();
      if (this.source[this.index] !== ":") {
        throw new Error("invalid JSON input: object key must be followed by colon");
      }
      this.index += 1;
      this.parseValue();
      this.skipWhitespace();
      if (this.source[this.index] === "}") {
        this.index += 1;
        return;
      }
      if (this.source[this.index] !== ",") {
        throw new Error("invalid JSON input: object entries must be separated by comma");
      }
      this.index += 1;
    }
    throw new Error("invalid JSON input: unterminated object");
  }

  private parseArray(): void {
    this.index += 1;
    this.skipWhitespace();
    if (this.source[this.index] === "]") {
      this.index += 1;
      return;
    }
    while (!this.isEnd()) {
      this.parseValue();
      this.skipWhitespace();
      if (this.source[this.index] === "]") {
        this.index += 1;
        return;
      }
      if (this.source[this.index] !== ",") {
        throw new Error("invalid JSON input: array values must be separated by comma");
      }
      this.index += 1;
    }
    throw new Error("invalid JSON input: unterminated array");
  }

  private parseString(): string {
    if (this.source[this.index] !== "\"") {
      throw new Error("invalid JSON input: string must start with quote");
    }
    this.index += 1;
    let output = "";
    while (!this.isEnd()) {
      const char = this.source[this.index] ?? "";
      this.index += 1;
      if (char === "\"") {
        return output;
      }
      if (char === "\\") {
        output += this.parseEscape();
        continue;
      }
      if (char < " ") {
        throw new Error("invalid JSON input: unescaped control character");
      }
      output += char;
    }
    throw new Error("invalid JSON input: unterminated string");
  }

  private parseEscape(): string {
    const escaped = this.source[this.index];
    this.index += 1;
    switch (escaped) {
      case "\"":
      case "\\":
      case "/":
        return escaped;
      case "b":
        return "\b";
      case "f":
        return "\f";
      case "n":
        return "\n";
      case "r":
        return "\r";
      case "t":
        return "\t";
      case "u": {
        const hex = this.source.slice(this.index, this.index + 4);
        if (!/^[0-9A-Fa-f]{4}$/u.test(hex)) {
          throw new Error("invalid JSON input: invalid unicode escape");
        }
        this.index += 4;
        return String.fromCharCode(Number.parseInt(hex, 16));
      }
      default:
        throw new Error("invalid JSON input: invalid string escape");
    }
  }

  private parseNumber(): void {
    const start = this.index;
    if (this.source[this.index] === "-") {
      this.index += 1;
    }
    if (this.source[this.index] === "0") {
      this.index += 1;
      if (isDigit(this.source[this.index])) {
        throw new Error("invalid JSON input: invalid number");
      }
    } else if (isDigitOneToNine(this.source[this.index])) {
      while (isDigit(this.source[this.index])) {
        this.index += 1;
      }
    } else {
      throw new Error("invalid JSON input: invalid number");
    }
    if (this.source[this.index] === ".") {
      this.index += 1;
      if (!isDigit(this.source[this.index])) {
        throw new Error("invalid JSON input: invalid number");
      }
      while (isDigit(this.source[this.index])) {
        this.index += 1;
      }
    }
    if (this.source[this.index] === "e" || this.source[this.index] === "E") {
      this.index += 1;
      if (this.source[this.index] === "+" || this.source[this.index] === "-") {
        this.index += 1;
      }
      if (!isDigit(this.source[this.index])) {
        throw new Error("invalid JSON input: invalid number");
      }
      while (isDigit(this.source[this.index])) {
        this.index += 1;
      }
    }
    const token = this.source.slice(start, this.index);
    const value = Number(token);
    if (!Number.isFinite(value)) {
      throw new Error("invalid JSON input: non-finite number");
    }
    if (Number.isInteger(value) && !Number.isSafeInteger(value)) {
      throw new Error("invalid JSON input: unsafe integer number");
    }
    if (jsonNumberExponentMagnitude(token) > 400) {
      throw new Error("invalid JSON input: lossy number");
    }
    if (canonicalJsonNumberToken(token) !== canonicalJsonNumberToken(String(value))) {
      throw new Error("invalid JSON input: lossy number");
    }
  }

  private consumeLiteral(literal: string): boolean {
    if (!this.source.startsWith(literal, this.index)) {
      return false;
    }
    this.index += literal.length;
    return true;
  }
}

function isDigit(value: string | undefined): boolean {
  return value !== undefined && value >= "0" && value <= "9";
}

function isDigitOneToNine(value: string | undefined): boolean {
  return value !== undefined && value >= "1" && value <= "9";
}

function jsonNumberExponentMagnitude(token: string): number {
  const exponentIndex = Math.max(token.indexOf("e"), token.indexOf("E"));
  if (exponentIndex < 0) {
    return 0;
  }
  const exponent = Number.parseInt(token.slice(exponentIndex + 1), 10);
  return Number.isFinite(exponent) ? Math.abs(exponent) : 401;
}

function canonicalJsonNumberToken(token: string): string {
  let remaining = token;
  let sign = "";
  if (remaining.startsWith("-")) {
    sign = "-";
    remaining = remaining.slice(1);
  }
  const exponentIndex = Math.max(remaining.indexOf("e"), remaining.indexOf("E"));
  let exponent = 0;
  if (exponentIndex >= 0) {
    exponent = Number.parseInt(remaining.slice(exponentIndex + 1), 10);
    remaining = remaining.slice(0, exponentIndex);
  }
  const dotIndex = remaining.indexOf(".");
  let integerPart = remaining;
  let fractionPart = "";
  if (dotIndex >= 0) {
    integerPart = remaining.slice(0, dotIndex);
    fractionPart = remaining.slice(dotIndex + 1);
  }
  const digits = integerPart + fractionPart;
  if (/^0+$/u.test(digits)) {
    return "0";
  }
  let decimalIndex = integerPart.length + exponent;
  let expanded: string;
  if (decimalIndex <= 0) {
    expanded = "0." + "0".repeat(-decimalIndex) + digits;
  } else if (decimalIndex >= digits.length) {
    expanded = digits + "0".repeat(decimalIndex - digits.length);
  } else {
    expanded = digits.slice(0, decimalIndex) + "." + digits.slice(decimalIndex);
  }
  const parts = expanded.split(".");
  const integer = (parts[0] ?? "").replace(/^0+/u, "") || "0";
  const fraction = (parts[1] ?? "").replace(/0+$/u, "");
  if (fraction !== "") {
    expanded = integer + "." + fraction;
  } else {
    expanded = integer;
  }
  return sign + expanded;
}

function nextCliValue<Key extends string>(
  argv: readonly string[],
  index: number,
  flag: string,
  config: ProofkitJsonReportCliParseConfig<Key>,
): string {
  const value = argv[index + 1];
  if (value === undefined || value.startsWith("--")) {
    throw new Error((config.missingValueMessage ?? ((name: string) => name + " requires a value"))(flag));
  }
  return value;
}

function admitCommand(command: string): void {
  if (command.length === 0 || command.startsWith("-") || command.includes("\0")) {
    throw new Error("agentic-proofkit command must be a non-empty command id");
  }
}

function admitRunOptions(options: ProofkitCommandRunOptions): void {
  if (options.binaryPath.length === 0) {
    throw new Error("Proofkit binaryPath is required");
  }
  if (options.cwd.length === 0) {
    throw new Error("Proofkit cwd is required");
  }
}

function formatReadFailure(filePath: string, error: unknown, options: ProofkitReportInputReadOptions): string {
  const message = redactSecretLikeText(filePath) + ": " + formatProofkitCliError(error);
  return options.failureMessagePrefix === undefined ? message : options.failureMessagePrefix + ": " + message;
}

function redactSecretLikeText(value: string): string {
  return value
    .replaceAll(/authorization\s*:\s*[^\r\n]+/giu, "authorization: [REDACTED]")
    .replaceAll(/bearer\s+[A-Za-z0-9._~+/=-]{8,}/giu, "Bearer [REDACTED]")
    .replaceAll(/(?:access[-_]?token|api[-_]?key|pass(?:word|wd)|secret|token)\s*[=:]\s*\S+/giu, "[REDACTED]")
    .replaceAll(/github_pat_[A-Za-z0-9_]+/giu, "[REDACTED]")
    .replaceAll(/gh[pousr]_[A-Za-z0-9_]+/giu, "[REDACTED]")
    .replaceAll(/sk-(?:proj-)?[A-Za-z0-9_-]{10,}/giu, "[REDACTED]")
    .replaceAll(/xox[abprs]-[A-Za-z0-9-]+/giu, "[REDACTED]")
    .replaceAll(/glpat-[A-Za-z0-9_-]+/giu, "[REDACTED]")
    .replaceAll(/[A-Za-z][A-Za-z0-9+.-]*:\/\/[^/\s:@]+:[^/\s@]+@/giu, "[REDACTED]")
    .replaceAll(/-----BEGIN [A-Z ]*PRIVATE KEY-----/giu, "[REDACTED]")
    .replaceAll(/eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+/giu, "[REDACTED]");
}
`
